import logo from './logo.svg';
// import './App.css';
import { React, Component } from 'react';
import {
	BrowserRouter as Router,
	Switch,
	Route,
	Link
} from "react-router-dom";


const routes = [
	{
		path: "/",
		exact: true,
		sidebar: () => <div></div>,
		main: () => <h2>Home</h2>
	},

	{
		path: "/users",
		sidebar: () => <div></div>,
		main: () => <div>

			<UserList initialUserData={[]} initialData={[]} userData={[]} accessToken={""} pollInterval={"5000"} />
		</div>
	}
];

class Results extends Component {
	render() {
		return (
			<div id="loadingLabel">
				<h5>Loading...</h5>
			</div>
		);
	}
}

class Dummy extends Component {
	render() {
		return (
			<div id="dummyLabel">
				<h5>Dummy</h5>
			</div>
		);
	}
}

class CommentBox extends Component {
	state = {
		data: this.props.initialData,
		userData: this.props.initialUserData,
		accessToken: this.props.accessToken,
		showLoading: false
	};

	componentDidMount() {
		
	}

	render() {
		
		return (

			<Router>
				<div>
					<nav className="navbar navbar-expand-md bg-dark navbar-dark">

						<a className="navbar-brand" href="#">ePIS Prototype</a>


						<button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
							<span className="navbar-toggler-icon"></span>
						</button>
						<div className="collapse navbar-collapse" id="collapsibleNavbar">
							<ul className="navbar-nav">
								<li className="navbar-item">
									<Link className="nav-link" to="/">Home</Link>
								</li>

								<li className="navbar-item">
									<Link className="nav-link" to="/users">Users</Link>
								</li>
							</ul>
						</div>
					</nav>

					<Switch>
						{routes.map((route, index) => (
							// You can render a <Route> in as many places
							// as you want in your app. It will render along
							// with any other <Route>s that also match the URL.
							// So, a sidebar or breadcrumbs or anything else
							// that requires you to render multiple things
							// in multiple places at the same URL is nothing
							// more than multiple <Route>s.
							<Route
								key={index}
								path={route.path}
								exact={route.exact}
								children={<route.sidebar />}
							/>
						))}
					</Switch>
				</div>

				<div style={{ flex: 1, padding: "10px" }}>
					<Switch>
						{routes.map((route, index) => (
							// Render more <Route>s with the same paths as
							// above, but different components this time.
							<Route
								key={index}
								path={route.path}
								exact={route.exact}
								children={<route.main />}
							/>
						))}
					</Switch>
				</div>


			</Router>
		);
	}
}

class Welcome extends Component {
	render() {
		return <h1>Hello, {this.props.name}</h1>;
	}
}

class CommentList extends Component {
	render() {
		var commentNodes = this.props.data.map(function (comment) {
			return (
				<Comment author={comment.author} key={comment.id}>
					{comment.text}
				</Comment>
			);
		});
		return <div className="commentList">{commentNodes}</div>;
	}
}

class UserList extends Component {
	state = {
		data: this.props.initialData,
		userData: this.props.initialUserData,
		accessToken: this.props.accessToken,
		showLoading: false
	};

	getTokenAndCallAPI = async () => {
		console.log("Loading data...");
		this.setState({ showLoading: true });
		window.setTimeout(function () { }, 1000);
		// Get access token to the API. 
		var myHeaders = new Headers();
		myHeaders.append("Content-Type", "text/plain");

		var raw = "grant_type=password&username=phonixadmin&password=Admin_123";

		var requestOptions = {
			method: 'POST',
			headers: myHeaders,
			body: raw,
			redirect: 'follow'
		};

		var userData2;

		if (this.state.accessToken.length == 0) {
			const token = await fetch("http://localhost/disha2adminapi/api/ApplicationUser/GetToken?userName=phonixadmin&password=Admin_123", requestOptions)
				.then(response => response.text())
				.catch(error => console.log('error', error));



			console.log("Token response: " + token);

			this.setState({ accessToken: JSON.parse(token).access_token });
		}

		let headers = { 'Accept': 'application/json', };
		if (this.state.accessToken) {
			headers["Authorization"] = `Bearer ${this.state.accessToken}`;
		}
		//console.log(headers);


		fetch("http://localhost/disha2adminapi/api/applicationuser/getinfolist", { headers, })
			.then(response => response.text())
			.then(result => {
				//console.log(result);
				userData2 = result;
				this.setState({ userData: JSON.parse(userData2), showLoading: false });

			})
			.catch(error => console.log('error', error));
	}

	loadCommentsFromServer = async () => {

		await this.getTokenAndCallAPI();

	};

	handleCommentSubmit = comment => {
		var comments = this.state.data;
		// Optimistically set an id on the new comment. It will be replaced by an
		// id generated by the server. In a production application you would likely
		// not use Date.now() for this and would have a more robust system in place.
		comment.id = Date.now();
		var newComments = comments.concat([comment]);
		this.setState({ data: newComments });

		var data = new FormData();
		data.append('author', comment.author);


		data.append('text', comment.text + " ");

		var xhr = new XMLHttpRequest();
		xhr.open('post', this.props.submitUrl, true);
		xhr.onload = function () {
			this.loadCommentsFromServer();
		}.bind(this);
		xhr.send(data);
	};

	componentDidMount() {
		window.setInterval(this.loadCommentsFromServer, this.props.pollInterval);
	}

	render() {
		const userData = this.state.userData.map(({ name, firstName, lastName, email, mobileNo, userId }) => ({ name, firstName, lastName, email, mobileNo }));

		return (
			<div className="container">
			<div className="row">
				<div className="col-md-8">
				<h3>List of Users</h3>
				<table className="table-bordered table-striped">
					<thead>
						<tr style={{ fontWeight: "bold" }}>
							<td>Name</td>
							<td>Mobile</td>
							<td>Email</td>
						</tr>
					</thead>
					<tbody>
						{userData.map((row, index) => (
							<tr key={index}>
								<td>{row.name}</td>
								<td>{row.mobileNo}</td>
								<td>{row.email}</td>
							</tr>
						))}
					</tbody>
				</table>
				</div>
			</div>
			</div>
		)
	}
}

class CommentForm extends Component {
	state = {
		author: '',
		text: ''
	};

	handleAuthorChange = e => {
		this.setState({ author: e.target.value });
	};

	handleTextChange = e => {
		this.setState({ text: e.target.value });
	};

	handleSubmit = e => {
		e.preventDefault();
		var author = this.state.author.trim();
		var text = this.state.text.trim();
		if (!text || !author) {
			return;
		}
		this.props.onCommentSubmit({ author: author, text: text });
		this.setState({ author: '', text: '' });
	};

	render() {
		return (
			<form className="commentForm" onSubmit={this.handleSubmit}>
				<h4>Add a New Comment below.</h4>
				<div class="row">
					<div class="col-md-3">
						<input
							type="text"
							placeholder="Your name"
							value={this.state.author}
							onChange={this.handleAuthorChange}
						/>
					</div>
					<div class="col-md-3">
						<input
							type="text"
							placeholder="Say something..."
							value={this.state.text}
							onChange={this.handleTextChange}
						/>

					</div>
				</div>
				<br />
				<div class="row">
					<div class="col-md-2">
						<input type="submit" value="Post" class="btn btn-primary" />
					</div></div>
			</form>
		);
	}
}

function createRemarkable() {
	var remarkable =
		'undefined' != typeof global && global.Remarkable
			? global.Remarkable
			: window.Remarkable;

	return new remarkable();
}

class Comment extends Component {
	rawMarkup = () => {
		var md = createRemarkable();
		var rawMarkup = md.render(this.props.children.toString());
		return { __html: rawMarkup };
	};

	render() {
		return (
			<div className="comment">
				<h2 className="commentAuthor">{this.props.author}</h2>
				<span dangerouslySetInnerHTML={this.rawMarkup()} />
			</div>
		);
	}
}

class User extends Component {

	render() {
		return (
			<div className="comment">
				<h4 className="commentAuthor">{this.props.name}</h4>
				<h5>{this.props.mobile}</h5>
			</div>
		);
	}
}


function App() {
	return (
		<div className="App">
			<header className="App-header">
				<img src={logo} className="App-logo" alt="logo" />
				<p>
					Edit <code>src/App.js</code> and save to reload.
				</p>
				<a
					className="App-link"
					href="https://reactjs.org"
					target="_blank"
					rel="noopener noreferrer"
				>
					Learn React faster
				</a>
			</header>
		</div>
	);
}

export default CommentBox;
